tap "homebrew/bundle"
tap "homebrew/services"
cask_args appdir: "~/Applications"

# Brews
brew 'awscli'
brew 'cocoapods'
brew 'composer'
brew 'fastfetch'
brew 'fish'
brew 'git'
brew 'gh'
brew 'lolcat'
brew 'openjdk@17'
brew 'opentofu'
brew 'php@8.3'
brew 'python'
brew 'tldr'

# Application Casks
cask '1password', args: { appdir: "/Applications" }
cask 'alfred'
cask 'altserver'
cask 'android-studio'
cask 'calibre'
cask 'claude-code'
cask 'dbeaver-community', greedy: true
cask 'discord'
cask 'docker-desktop'
cask 'firefox'
cask 'iina'
cask 'iterm2'
cask 'itermai', args: { appdir: "/Applications" }
cask 'jetbrains-toolbox'
cask 'monodraw'
cask 'mullvad-vpn'
cask 'notion'
cask 'obsidian'
cask 'plex'
cask 'raycast'
cask 'signal'
cask 'slack'
cask 'steam'
cask 'spotify'
cask 'tailscale-app'
cask 'the-unarchiver'
cask 'visual-studio-code@insiders'
cask 'yaak'
cask 'zoom'

# Font Casks
cask 'font-meslo-lg-nerd-font'
cask 'font-monaspace'
