tap "homebrew/bundle"
tap "homebrew/services"
cask_args appdir: "~/Applications"

# Brews
brew 'awscli'
brew 'fastfetch'
brew 'fish'
brew 'git'
brew 'gh'
brew 'lolcat'
brew 'tldr'

# Application Casks
cask '1password', args: { appdir: "/Applications" }
cask 'alfred'
cask 'altserver'
cask 'dbeaver-community', greedy: true
cask 'discord'
cask 'docker-desktop'
cask 'firefox'
cask 'google-chrome'
cask 'iina'
cask 'insomnia'
cask 'iterm2'
cask 'itermai', args: { appdir: "/Applications" }
cask 'jetbrains-toolbox'
cask 'microsoft-teams'
cask 'microsoft-auto-update'
cask 'miro'
cask 'mullvad-vpn'
cask 'obsidian'
cask 'plex'
cask 'slack'
cask 'steam'
cask 'spotify'
cask 'tailscale-app'
cask 'the-unarchiver'
cask 'visual-studio-code@insiders'
cask 'volanta'
cask 'zoom'

# Font Casks
cask 'font-meslo-lg-nerd-font'
cask 'font-monaspace'
