tap "homebrew/bundle"
tap "homebrew/services"
cask_args appdir: "~/Applications"

# Brews
brew 'awscli'
brew 'fastfetch'
brew 'fish'
brew 'git'
brew 'gh'
brew 'lolcat'
brew 'tldr'

# Application Casks
cask '1password', args: { appdir: "/Applications" }
cask 'alfred'
cask 'firefox'
cask 'iina'
cask 'iterm2'
cask 'itermai', args: { appdir: "/Applications" }
cask 'miro'
cask 'mullvadvpn'
cask 'obsidian'
cask 'plex'
cask 'slack'
cask 'steam'
cask 'spotify'
cask 'stats'
cask 'the-unarchiver'
cask 'visual-studio-code@insiders'

# Font Casks
cask 'font-meslo-lg-nerd-font'
cask 'font-monaspace'
